# Generated by Django 3.2.9 on 2022-02-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JuntaDirectiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=1000)),
                ('nombre_representante', models.CharField(max_length=200)),
                ('fotografia', models.ImageField(upload_to='junta-directiva')),
                ('electivo', models.DateField()),
                ('puesto', models.IntegerField(choices=[(1, 'PRESIDENTE'), (2, 'VICE PRESIDENTE'), (3, 'SECRETARIA'), (4, 'TESORERA'), (5, 'VOCAL 1'), (6, 'VOCAL 2'), (7, 'VOCAL 3')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'Publicado'), (1, 'Ocultar')], default=0)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
