# Generated by Django 3.2.9 on 2022-02-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntadirectiva', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='juntadirectiva',
            options={'verbose_name': 'Junta Directiva'},
        ),
        migrations.RemoveField(
            model_name='juntadirectiva',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='juntadirectiva',
            name='titulo',
        ),
        migrations.AlterField(
            model_name='juntadirectiva',
            name='fotografia',
            field=models.ImageField(upload_to='juntad'),
        ),
        migrations.AlterField(
            model_name='juntadirectiva',
            name='puesto',
            field=models.IntegerField(choices=[(0, ''), (1, 'PRESIDENTE'), (2, 'VICE PRESIDENTE'), (3, 'SECRETARIA'), (4, 'TESORERA'), (5, 'VOCAL 1'), (6, 'VOCAL 2'), (7, 'VOCAL 3')], default=0),
        ),
    ]
