# Generated by Django 3.2.9 on 2022-02-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolsa_De_Empleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('cargar_archivo', models.FileField(blank=True, null=True, upload_to='media/')),
                ('descripcion', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(0, 'Publicado'), (1, 'Ocultar')], default=0)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bolsa de empleo y TDRS',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_noticia', models.CharField(max_length=200)),
                ('imagen_principal', models.ImageField(upload_to='noticias_imagenes')),
                ('descripcion', models.CharField(max_length=1000)),
                ('enlace', models.CharField(blank=True, max_length=200, null=True)),
                ('categoria', models.IntegerField(choices=[(0, 'Noticias'), (1, 'Información Pública')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'Publicado'), (1, 'Ocultar')], default=0)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Noticias',
            },
        ),
    ]
