# Generated by Django 3.2.9 on 2022-02-27 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bolsa_De_Empleo',
            new_name='BolsaDeEmpleo',
        ),
        migrations.AlterModelOptions(
            name='noticia',
            options={'verbose_name': 'Noticia'},
        ),
    ]
