# Generated by Django 3.2.9 on 2022-03-07 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Nombre de la categoria',
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('enlace', models.CharField(blank=True, max_length=200, null=True)),
                ('cargar_archivo', models.FileField(blank=True, null=True, upload_to='infopublica/')),
                ('status', models.IntegerField(choices=[(0, 'Publicado'), (1, 'Ocultar')], default=0)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoriainfopublic', to='infopublic.categoria')),
            ],
            options={
                'verbose_name': 'Información Pública',
            },
        ),
    ]
