# Generated by Django 3.2.9 on 2022-02-27 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejeproyectos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LugarEjecicion',
            new_name='LugarEjecucion',
        ),
        migrations.AlterModelOptions(
            name='eje',
            options={'verbose_name': 'Ejes', 'verbose_name_plural': 'Ejes'},
        ),
        migrations.AlterModelOptions(
            name='lugarejecucion',
            options={'verbose_name': 'Lugar de ejecución', 'verbose_name_plural': 'Lugar de ejecución'},
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='galeria',
        ),
        migrations.CreateModel(
            name='PostGaleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenes', models.FileField(upload_to='proyectos/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ejeproyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Fotografias',
            },
        ),
    ]
